name: federation-v1
on:
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: federation-v1-${{ github.ref }}
  cancel-in-progress: true

jobs:
  subgraphs:
    uses: ./.github/workflows/docker-bake.template.yaml
    with:
      dir: federation-v1/subgraphs
      hcl: docker.hcl
      target: subgraphs

  decide-runner:
    needs: subgraphs
    uses: ./.github/workflows/decide-runner.template.yaml

  constant-vus-over-time:
    needs:
      - decide-runner
      - subgraphs
    strategy:
      fail-fast: false
      matrix:
        directory:
          - apollo-server
          - apollo-router
          - hive-gateway
          - cosmo
          - mercurius
          - grafbase
          - inigo
    uses: ./.github/workflows/benchmark.template.yaml
    with:
      gateway: ${{ matrix.directory }}
      vu: 300
      time: ${{ github.event_name == 'pull_request' && '30s' || '60s' }}
      baseDir: federation-v1
      scenarioDir: constant-vus-over-time
      scenarioName: constant-vus-over-time
      runner: ${{ needs.decide-runner.outputs.runner }}
      cpuLimit: 2
      memoryLimit: 4gb

  constant-vus-over-time-report:
    needs: constant-vus-over-time
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioName: constant-vus-over-time
      baseDir: federation-v1
      scenarioDir: constant-vus-over-time

  constant-vus-subgraphs-delay:
    needs:
      - decide-runner
      - subgraphs
    strategy:
      fail-fast: false
      matrix:
        directory:
          - apollo-server
          - apollo-router
          - hive-gateway
          - cosmo
          - mercurius
          - grafbase
    uses: ./.github/workflows/benchmark.template.yaml
    with:
      gateway: ${{ matrix.directory }}
      vu: 300
      time: ${{ github.event_name == 'pull_request' && '30s' || '60s' }}
      baseDir: federation-v1
      scenarioDir: constant-vus-over-time
      scenarioName: constant-vus-subgraphs-delay
      runner: ${{ needs.decide-runner.outputs.runner }}
      cpuLimit: 2
      memoryLimit: 4gb
      subgraphDelayRange: "40~150"

  constant-vus-subgraphs-delay-report:
    needs: constant-vus-subgraphs-delay
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioName: constant-vus-subgraphs-delay
      baseDir: federation-v1
      scenarioDir: constant-vus-over-time

  constant-vus-subgraphs-delay-resources:
    needs:
      - decide-runner
      - subgraphs
    strategy:
      fail-fast: false
      matrix:
        directory:
          - apollo-server
          - apollo-router
          - hive-gateway
          - cosmo
          - mercurius
          - grafbase
    uses: ./.github/workflows/benchmark.template.yaml
    with:
      gateway: ${{ matrix.directory }}
      vu: 500
      time: ${{ github.event_name == 'pull_request' && '30s' || '60s' }}
      baseDir: federation-v1
      scenarioDir: constant-vus-over-time
      scenarioName: constant-vus-subgraphs-delay-resources
      runner: ${{ needs.decide-runner.outputs.runner }}
      cpuLimit: 4
      memoryLimit: 8gb
      subgraphDelayRange: "40~150"

  constant-vus-subgraphs-delay-resources-report:
    needs: constant-vus-subgraphs-delay-resources
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioName: constant-vus-subgraphs-delay-resources
      baseDir: federation-v1
      scenarioDir: constant-vus-over-time

  ramping-vus:
    needs:
      - decide-runner
      - subgraphs
    strategy:
      fail-fast: false
      matrix:
        directory:
          - apollo-server
          - apollo-router
          - hive-gateway
          - cosmo
          - mercurius
          - grafbase
    uses: ./.github/workflows/benchmark.template.yaml
    with:
      gateway: ${{ matrix.directory }}
      vu: 2000
      time: 60s
      baseDir: federation-v1
      scenarioDir: ramping-vus
      scenarioName: ramping-vus
      runner: ${{ needs.decide-runner.outputs.runner }}
      cpuLimit: 4
      memoryLimit: 8gb

  ramping-vus-report:
    needs: ramping-vus
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioName: ramping-vus
      scenarioDir: ramping-vus
      baseDir: federation-v1
